### ISSUE TITLE
Explicit version in composer.json

### ISSUE THREAD

**Issue by Maikuolan** [91ahmed/JsonModifier#1]
https://github.com/91ahmed/JsonModifier/blob/79e6c0954bfbb980b74cd0d8a99a3857ab634520/composer.json#L4

*See: https://packagist.org/about#managing-package-versions*

> ### Managing package versions
> New versions of your package are automatically fetched from tags you create in your VCS repository.
> 
> The easiest way to manage versioning is to just omit the version field from the composer.json file. The version numbers will then be parsed from the tag and branch names.

Might be better to remove that line and just create new [tags](https://github.com/91ahmed/JsonModifier/tags) for new versions here instead.

**Comment by 91ahmed** [comment]
Thanks for your notes, I'll remove it.

**Comment by Maikuolan** [comment]
*Resolved by 6e78b122a9ae9377ce23c2a0b8a8b7ad60eb6521.*
