### ISSUE TITLE
Vendor and composer.lock

### ISSUE THREAD

**Issue by Maikuolan** [91ahmed/JsonModifier#3]
Being (per Packagist definitions) a "library" as opposed to a "project" (i.e., being something you would `composer require` as a dependency into a project in order to benefit from the functionality provided by the package, as opposed to being the other way around whereby it would have dependencies of its own but not be appropriate for inclusion as a dependency into something else), you probably won't need the `vendor` directory or `composer.lock` files at the repository here.

You could keep them if you wanted them, but if they were deleted entirely, I don't think it would have any actual impact on the functionality of your code at all.

**Comment by 91ahmed** [comment]
Thanks for contribution, It was my first time to create a composer package, I totally forgot about many things.

**Comment by Maikuolan** [comment]
*Resolved by 666f3e8726097a3b09cbe15123ce8ca8e9e62e8e.*
